### ISSUE TITLE
Module Request: ngx_dynamic_limit_req_module

### ISSUE THREAD

**Issue by droplinxuser** [eilandert/deb.myguard.nl#10]
More info:
https://github.com/limithit/ngx_dynamic_limit_req_module

The ngx_dynamic_limit_req_module module is used to dynamically lock IP and release it periodically.

**Comment by eilandert** [comment]
I have added that only in nginx now, can you test it?  I'm building and uploading now
apt install libnginx-mod-http-dynamic-req

If it works I'll incorporate it into Angie

**Comment by droplinxuser** [comment]
Thanks for the update.
I'm on Ubuntu 24.04, and I got this:

> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> E: Unable to locate package libnginx-mod-http-dynamic-req

**Comment by droplinxuser** [comment]
The correct name I think is: libnginx-mod-http-dynamic-limit-req

**Comment by droplinxuser** [comment]
So it's intended and required to have "libhiredis1.1.0" installed also?

**Comment by droplinxuser** [comment]
Nginx failed to reload also.
```
# nginx -t
2024/10/01 19:15:27 [emerg] 38158#38158: dlopen() "/usr/share/nginx/modules/ngx_dynamic_limit_req_module.so" failed (/usr/share/nginx/modules/ngx_dynamic_limit_req_module.so: cannot open shared object file: No such file or directory) in /etc/nginx/modules-enabled/50-mod-http-dynamic-limit-req.conf:1
nginx: configuration file /etc/nginx/nginx.conf test failed
```

**Comment by droplinxuser** [comment]
It's looking for:
/usr/share/nginx/modules/ngx_dynamic_limit_req_module.so

When the actual file is:
/usr/share/nginx/modules/ngx_http_dynamic_limit_req_module.so

**Comment by droplinxuser** [comment]
After correcting the config/file name:
/etc/nginx/modules-enabled/50-mod-http-dynamic-limit-req.conf

The module works great as I tested; thank you so much for adding this one.

**Comment by eilandert** [comment]
Thanks :-)  I corrected it.

**Comment by eilandert** [comment]
This is added to Angie, the website and the changelog as well, I close this issue but feel free to open it again if there is something wrong.

**Comment by droplinxuser** [comment]
Hi,

I don't see it listed here:
https://deb.myguard.nl/nginx-modules/

**Comment by eilandert** [comment]
it's there, look for [libnginx-mod-http-dynamic-limit-req](https://www.github.com/limithit/ngx_dynamic_limit_req_module) :)
