### ISSUE TITLE
Is there any available changelog?

### ISSUE THREAD

**Issue by Arien02** [eilandert/deb.myguard.nl#12]
Hi!
This week I received an update for some nginx addon packages, but I cannot see any changelog:

`Des:2 http://deb.myguard.nl bookworm/main amd64 libnginx-mod-http-brotli amd64 3:1.27.1-1myguard3~bookworm [114 kB]
Des:3 http://deb.myguard.nl bookworm/main amd64 libnginx-mod-http-modsecurity amd64 3:1.27.1-1myguard3~bookworm [90,4 kB]
Des:4 http://deb.myguard.nl bookworm/main amd64 libnginx-mod-http-security-headers amd64 3:1.27.1-1myguard3~bookworm [86,0 kB]
Des:5 http://deb.myguard.nl bookworm/main amd64 libnginx-mod-http-zstd amd64 3:1.27.1-1myguard3~bookworm [115 kB]
Des:6 http://deb.myguard.nl bookworm/main amd64 libnginx-mod-pagespeed amd64 3:1.27.1-1myguard3~bookworm [3.830 kB]`

But nginx main package is not changed at all, is there any reason for this update?
Thank you!

**Comment by droplinxuser** [comment]
Major changes is added to github homepage, but no logs about this tiny updates though.

https://github.com/eilandert/deb.myguard.nl

**Comment by eilandert** [comment]
the latest change is the addition of ngx_dynamic_limit_req_module

but because I haven;t updated the angie build and some documentation I haven't documented it yet

**Comment by Arien02** [comment]
Thank you!
