### ISSUE TITLE
angie not built with all dynamic modules

### ISSUE THREAD

**Issue by schories** [eilandert/deb.myguard.nl#15]
Hello Thijs,

as far as I understand angie (same for nginx) 

1. has to be already built with dynamically linked modules, to be able to add & enable those when required later.

2. Additionally, "angie" (respectively nginx) is the main package now - former "light, core, full, .." are [deprecated](https://metadata.ftp-master.debian.org/changelogs//main/n/nginx/nginx_1.22.1-9_changelog).

The current angie 1.7.0 version in your great repo, however, was "only" built with the following 5 dynamic modules:

- http_image_filter_module
- http_geoip_module
- http_perl_module
- http_xslt_module
- stream_geoip_module

` angie -V 2>&1|xargs -n1|grep module`

--modules-path=/usr/lib/angie/modules
--with-http_acme_module
--with-http_dav_module
--with-http_ssl_module
--with-http_v2_module
--with-http_v3_module
--with-stream_realip_module
--with-stream_ssl_module
--with-stream_ssl_preread_module
--with-http_addition_module
--with-http_auth_request_module
--with-http_degradation_module
--with-http_flv_module
--with-http_geoip_module=dynamic
--with-http_gunzip_module
--with-http_gzip_static_module
--with-http_image_filter_module=dynamic
--with-http_mp4_module
--with-http_perl_module=dynamic
--with-http_random_index_module
--with-http_realip_module
--with-http_secure_link_module
--with-http_slice_module
--with-http_stub_status_module
--with-http_sub_module
--with-http_xslt_module=dynamic
--with-mail_ssl_module
--with-stream_geoip_module=dynamic`

Means, installing additional modules later e.g., for zstd, works on the command line

`apt-get install  angie-module-http-zstd`

but the module won't be truly available after installation, however.

I apologize, but I haven't found the exact setting in your repo(s) to add all the additional modules as dynamic during the build.

Can you please add them? :pray: Otherwise, in case I am wrong, please let me know also.

Thank you once again!

Alexander

**Comment by schories** [comment]
Debian Bookworm is affected in my case. Haven't tested other releases.

**Comment by eilandert** [comment]
Hi, did you do a full apt update && apt upgrade?  I updated Angie today for your changes :-)

The modules are built in the same package (see debian/rules), should not be a problem. I just tested it in a bookworm docker.
This package is based on the NGINX package from Trixie, I only brought back the -full -extra etc as wrapper in the control-file (debian/control), not as compile option. However I added a angie-minimal on request in debian/rules.

Let me know if it still not works

**Comment by schories** [comment]
Hi,

> Hi, did you do a full apt update && apt upgrade? 

Yes, exactly.

> I updated Angie today for your changes :-)

I immediately saw it and use them already - thank you, Thijs!

> The modules are built in the same package (see debian/rules), should not be a problem. I just tested it in a bookworm docker.
This package is based on the NGINX package from Trixie, I only brought back the -full -extra etc as wrapper in the control-file (debian/control), not as compile option. However I added a angie-minimal on request in debian/rules.

I see, that fits.

> Let me know if it still not works

Of course. And thank you once again.

**Comment by schories** [comment]
- Double checked:  "angie 3:1.7.0-4myguard3~bookworm  amd64" is affected, means it is "only" built to handle those 5 dynamic modules above

- The current build is based on "bin_configure_flags" in debian/release.

- However, as we only build 1 single binary now - and full/minimal/light became just meta packages for backwards compatibility - this build must be prepared for all dynamic modules now. Thus I basically took all settings from "modules_configure_flags" and used them for "bin_configure_flags" in debian/release. Added a comment and kept the old config commented out for reference. The commit has been pushed to your repo. Not urgent, sorry for bothering you - I hope to get more familiar with all this quickly.

Thank you!

**Comment by eilandert** [comment]
Hi,

Besides it doesn;t compile anymore...  you have to edit all the *.install files and probably more to point to the right path of the .so

We should probably work with a dev-branch and do pull requests so we can test things. :)

**Comment by eilandert** [comment]
oh and lets have these conversations in the right repo
