### ISSUE TITLE
"ngx_http_hls_module" similar module available?

### ISSUE THREAD

**Issue by droplinxuser** [eilandert/deb.myguard.nl#4]
Hi,

Does this repo offer a third-party module that works similar to ngx_http_hls_module?

More info:
https://nginx.org/en/docs/http/ngx_http_hls_module.html

I don't see any mention of HLS here:
https://deb.myguard.nl/nginx-modules/

**Comment by eilandert** [comment]
Hi,

The module you are referring to is only for commercial subscribers of F5 ;-(

I have no experience with HLS, but you could try this module: https://github.com/winshining/nginx-http-flv-module.
It's installable as libnginx-mod-http-flv-live
