### ISSUE TITLE
Error: gzip filter failed to use preallocated memory

### ISSUE THREAD

**Issue by droplinxuser** [eilandert/deb.myguard.nl#5]
Anyone experience this kind of error?

`[alert] 41728#41728: *88646 gzip filter failed to use preallocated memory: 350272 of 336176 while sending to client, client: 1:2:3::4, server: dom.com, request: "GET /url/title/ HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "dom.com"`

I'm not sure what configuration to adjust.

**Comment by droplinxuser** [comment]
My gzip config:

```
gzip on;
gzip_buffers 1024 8k;
gzip_comp_level 5;
gzip_min_length 48;
gzip_proxied any;
gzip_vary on;
```

**Comment by droplinxuser** [comment]
It seems this error was fixed 3 times already based on these logs:
https://nginx.org/en/CHANGES

**Comment by eilandert** [comment]
Hi, thanks for your report.

I see the same (I checked thanks to you), there was a zlib-ng update yesterday, maybe thats the problem.

I'll have to finish something else first, I'll take a look at it later today

**Comment by eilandert** [comment]
I'm building zlib-ng 2.1.7 now,  seems 2.2.x is a new branch which has a feature what conflicts with nginx's own memory allocator.

It's building now, when finished I will build new dockers also

**Comment by droplinxuser** [comment]
Please also include the Ubuntu PPA :)
https://launchpad.net/~eilander/+archive/ubuntu/nginx

Thank you.

**Comment by eilandert** [comment]
Ai thats a problem, I see they are rejected because 1.7 is lower than 2.2 :s   I'll see what I can do

**Comment by eilandert** [comment]
> Ai thats a problem, I see they are rejected because 1.7 is lower than 2.2 :s I'll see what I can do

Ok, deleted the new packages and copied the old superseded 2.1.7 packages back. The status is Pending but should be there soon.

**Comment by eilandert** [comment]
For future reference:

https://github.com/zlib-ng/zlib-ng/releases/tag/2.2.0

"It also means that applications that replace the alloc/free functions with their own can potentially have some issues (Yes I am looking at you Nginx)."

**Comment by droplinxuser** [comment]
Hi, I'm not sure what happens, but the package seems gone? On my Ubuntu 24.04 install.

```
# apt list --installed | grep zlib*
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

zlib1g/noble,now 1:1.3.dfsg-3.1ubuntu2 amd64 [installed,automatic]
```

```
# apt install -y nginx-minimal libnginx-mod-http-brotli libnginx-mod-http-trim-filter --no-install-recommends
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
nginx-minimal is already the newest version (3:1.27.0-1myguard1~noble).
libnginx-mod-http-brotli is already the newest version (3:1.27.0-1myguard1~noble).
libnginx-mod-http-trim-filter is already the newest version (3:1.27.0-1myguard1~noble).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by droplinxuser** [comment]
How do I downgrade this zlib?
It's labelled as local now.

```
# apt list --installed | grep myguard*

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libmaxminddb0/noble,now 1.10.0-3myguard1~noble amd64 [installed,automatic]
libnginx-mod-http-brotli/noble,now 3:1.27.0-1myguard1~noble amd64 [installed]
libnginx-mod-http-trim-filter/noble,now 3:1.27.0-1myguard1~noble amd64 [installed]
libssl3/noble,now 3.0.14-10myguard28~noble amd64 [installed,automatic]
libz-ng2/now 2.2.1-3myguard1~noble amd64 [installed,local]
nginx-common/noble,now 3:1.27.0-1myguard1~noble amd64 [installed,automatic]
nginx-minimal/noble,now 3:1.27.0-1myguard1~noble amd64 [installed]
openssl/noble,now 3.0.14-10myguard28~noble amd64 [installed,automatic]
```

**Comment by droplinxuser** [comment]
I also tried doing:

```
# apt install --reinstall libz-ng2
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Reinstallation of libz-ng2 is not possible, it cannot be downloaded.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by eilandert** [comment]
I'm not an apt hero, but try apt-get install libz-ng2=2.1.7

**Comment by droplinxuser** [comment]
Thanks; it's solved now.
```
apt list -a | grep libz-ng2
apt install libz-ng2=2.1.7-3myguard1~jammy
```
