### ISSUE TITLE
Do you support Nginx stable version?

### ISSUE THREAD

**Issue by joglomedia** [eilandert/deb.myguard.nl#7]
Hi @eilandert 

Is it possible to support Nginx stable version?

Because Nginx has two versioning, mainline and stable

Regards

**Comment by droplinxuser** [comment]
I’ve been using the nginx mainline version since 2013 and it’s rock solid and very stable for production usage. 

If I would like to have the best possible bug free Nginx, I would use the one provided by the OS repository.

**Comment by eilandert** [comment]
At the moment, no.

Main reason: I can't serve 2 nginx's on one ppa at the moment, 
I need to make drastic changes to the infrastructure to make that possible
